source 'https://github.com/CocoaPods/Specs.git'
source 'git@www.ios-repo.dev:ip-ios/pods-repo.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '8.0'


target 'ObjectPool_Example' do

    pod 'ObjectPool', :path => '../', :inhibit_warnings => false

    target 'ObjectPool_Tests' do
        inherit! :search_paths

	
    end

end







